/*
 - Data Model for Visitor Entity
 - This class represents the structure of our visitor data
 - It maps directly to the columns in our PostgreSQL database table
 */
namespace VisitorsReg.Models;

public class Visitor
{
    // Unique identifier for each visitor - automatically generated by database
    public int Id { get; set; }

    // Visitor's name - validated to be one word, letters only
    public string Name { get; set; } = string.Empty;

    // Visitor's email address - validated for proper email format
    public string Email { get; set; } = string.Empty;

    // Timestamp of when the visitor registered - automatically set by database
    public DateTime RegisteredAt { get; set; }
}
